mensaje=Estoy desplegando en pruebas

URL_API=https://test-api-autozone.com/productos

spring.application.name=JavaCourse2025
spring.datasource.url=jdbc:mysql://localhost:3306/dev
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
